#! /bin/bash

cd /mnt/f/General_Storage/rcdb-docs/docs
make html
make latexpdf
cd /mnt/f/General_Storage/rcdb-docs/docs/build/html
zip -r rcdb-docs-html.zip *
mv rcdb-docs-html.zip ../../..
cd ../latex
mv rcdb-docs.pdf ../../..
cd ../../..