name: "Build Docs"

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      deployments: write
      issues: write

    steps:
    - uses: actions/checkout@v4

    # Build HTML
    - name: Build HTML
      uses: ammaraskar/sphinx-action@master

    # Upload artifacts (HTML)
    - name: Upload HTML
      uses: actions/upload-artifact@v4
      with:
        name: HTML Documentation
        path: docs/build/html/

    # Deploy
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html

    # Build PDF
    - name: Build PDF
      uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "apt-get update -y && apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended"
        build-command: "make latexpdf"

    # Upload artifacts (PDF)
    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: PDF Documentation
        path: docs/build/latex/rcdb-docs.pdf