name: "Build Docs"

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      deployments: write
      issues: write

    steps:
    - uses: actions/checkout@v4

    # Build HTML
    - name: Build HTML
      uses: ammaraskar/sphinx-action@master

    # Upload artifacts (HTML)
    - name: Upload HTML
      uses: actions/upload-artifact@v4
      with:
        name: HTML Documentation
        path: docs/build/html/

    # Deploy
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html

    # Build PDF
    - name: Build LaTeX
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs"
        pre-build-command: "touch /tmp/sphinx-log && apt-get update -y && apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended"
        build-command: "sphinx-build source build/latex -b latex"

    - name: Make PDF
      uses: xu-cheng/texlive-action@v2
      with:
        scheme: full
        run: |
          cd docs/build/latex
          make

    # Upload and release artifacts (PDF)
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_number }}-${{ github.event.repository.name }}
        release_name: Release ${{ github.run_number }}-${{ github.event.repository.name }}
        body: "This is an automated release of the RCDB PDF Documentation"
        draft: false
        prerelease: false

    - name: Upload PDF
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: "docs/source/build/latex/rcdb-docs.pdf"
        asset_name: "rcdb-docs.pdf"
        asset_content_type: "application/pdf"