name: "Build Docs"

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    # Install dependencies
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx
        sudo apt-get install texlive-latex-recommended texlive-fonts-recommended

    # Build HTML
    - name: Build HTML
      uses: ammaraskar/sphinx-action@master

    # Build LaTeX PDF
    - name: Build LaTeX PDF
      run: |
        cd docs
        make latexpdf

    # Upload artifacts (HTML)
    - name: Upload HTML artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rcdb-docs-html
        path: docs/build/html/

    # Upload artifacts (PDF)
    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: PDF Documentation
        path: docs/build/latex/rcdb-docs.pdf

    # Deploy
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html
